name: publish

on:
  push:
    branches:
      - main
      - master

jobs:
  publish-github-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the github-runner Docker image
        run: |
          docker build --build-arg RUNNER_VERSION=2.307.1 --tag ghcr.io/zerka30/github-runner:latest .

      - name: Start the github-runner container
        run: |
          docker run ghcr.io/zerka30/github-runner:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/zerka30/github-runner:latest